name: daftar_siswa
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  drift: ^2.34.3
  drift_flutter: ^0.3.1
  flutter:
    sdk: flutter
  path_provider: ^2.1.6
  provider: ^6.1.5+1
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.34.5
  build_runner: ^2.15.1

flutter:
  uses-material-design: true
  assets:
    - assets/profile.jpg

